/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#ffb783",
        "on-error": "#690005",
        "on-surface": "#dae2fd",
        "surface-variant": "#2d3449",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "surface-container-low": "#131b2e",
        "on-primary-fixed": "#07006c",
        "on-secondary": "#3c0091",
        "on-primary-container": "#0d0096",
        "surface-container": "#171f33",
        "on-background": "#dae2fd",
        "error-container": "#93000a",
        "tertiary-container": "#d97721",
        "primary-container": "#8083ff",
        "surface-bright": "#31394d",
        "on-primary-fixed-variant": "#2f2ebe",
        "primary-fixed-dim": "#c0c1ff",
        secondary: "#d0bcff",
        "on-tertiary-fixed-variant": "#703700",
        "outline-variant": "#464554",
        "on-secondary-fixed-variant": "#5516be",
        "surface-dim": "#0b1326",
        "on-secondary-fixed": "#23005c",
        "secondary-fixed-dim": "#d0bcff",
        "primary-fixed": "#e1e0ff",
        surface: "#0b1326",
        background: "#0b1326",
        "tertiary-fixed-dim": "#ffb783",
        "on-surface-variant": "#c7c4d7",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#060e20",
        primary: "#c0c1ff",
        error: "#ffb4ab",
        "surface-container-highest": "#2d3449",
        "on-secondary-container": "#c4abff",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-fixed": "#301400",
        outline: "#908fa0",
        "secondary-container": "#571bc1",
        "inverse-surface": "#dae2fd",
        "on-tertiary-container": "#452000",
        "on-primary": "#1000a9",
        "surface-tint": "#c0c1ff",
        "secondary-fixed": "#e9ddff",
        "inverse-primary": "#494bd6",
        "on-tertiary": "#4f2500",
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
